database: hsqldb

# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org:
        springframework.web: debug

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false